name: 'surgical_data_mesh'
version: '1.0.0'
config-version: 2

profile: 'surgical_data_mesh'

model-paths: ["models"]

models:
  surgical_data_mesh:
    staging:
      +materialized: view
    marts:
      +materialized: table
